### ISSUE TITLE
every time i change the code i have to reopen devtools

### ISSUE THREAD

**Issue by ahmedsayedabdelsalam** [Te7a-Houdini/alpinejs-devtools#49] opened 2020-05-09 18:09 UTC
os: macOs
browser: chrome

**Comment by HugoDF** [comment] 2020-05-09 18:24
Is this a duplicate of https://github.com/Te7a-Houdini/alpinejs-devtools/issues/1?

**Closed** 2020-05-09 18:28 UTC
